#WHY LEARN DATASTRUCTURES?
#Store multiple items or data in a memory space using collections.
#A way of storing multiple items together.
#     TYPES OF DATA STRUCTURES

#1.LIST.
#--UNORDERED AND MUTABLE COLLECTION OF ITEMS OF DIFFERENT DATATYPES.
#THIS COMES TO ITEMS OF ANY TYPE.
#-LIST IS DENOTED BY SQUARE BRACKET[].
#-FOR EXAMPLE YOU CAN HAVE A LIST OF FRUITS.
#fruits=[apple,banana,apple].
#properties of list.
#1.ordered-uses index to access items.
#2.They can store items of any datatype.-contains items["mary",1,2,3,false],
#3.Store many datatypes.
#4.They are mutable-values in the list can be changed.
#5.values in a list are accessed using index.
#values in a list are comma(,) separated
#A list can also contain another list, this is what we call a,NESTED LIST

  # LIST OPERATIONS
#ADDING ITEMS TO A LIST.
#1.append()adds items at the end of a list
#2.extends()adds multiple items
#3.insert()

#2.TUPLE.
#3.DICTIONARY.
#4.SETS.

